window.KYOTEI_DATA = {
  "updated": "2026-06-29 05:55",
  "today_label": "2026年6月29日",
  "pred_date": "2026/06/29",
  "pred_is_today": true,
  "week_label": "6/29（月）〜7/5（日）",
  "month_label": "2026年6月",
  "ev_threshold": 1.3,
  "weekly_demo": {
    "total_bets": 0,
    "total_hits": 0,
    "total_invested": 0,
    "total_returned": 0,
    "roi": -100.0,
    "daily": [],
    "start_label": "6/29",
    "end_label": "7/5"
  },
  "monthly_demo": {
    "total_bets": 122,
    "total_hits": 0,
    "total_invested": 12200,
    "total_returned": 0,
    "roi": -100.0,
    "daily": [
      {
        "date": "6/22",
        "bets": 25,
        "hits": 0,
        "invested": 2500,
        "returned": 0,
        "roi": -100.0
      },
      {
        "date": "6/23",
        "bets": 16,
        "hits": 0,
        "invested": 1600,
        "returned": 0,
        "roi": -100.0
      },
      {
        "date": "6/24",
        "bets": 6,
        "hits": 0,
        "invested": 600,
        "returned": 0,
        "roi": -100.0
      },
      {
        "date": "6/25",
        "bets": 5,
        "hits": 0,
        "invested": 500,
        "returned": 0,
        "roi": -100.0
      },
      {
        "date": "6/26",
        "bets": 20,
        "hits": 0,
        "invested": 2000,
        "returned": 0,
        "roi": -100.0
      },
      {
        "date": "6/27",
        "bets": 25,
        "hits": 0,
        "invested": 2500,
        "returned": 0,
        "roi": -100.0
      },
      {
        "date": "6/28",
        "bets": 25,
        "hits": 0,
        "invested": 2500,
        "returned": 0,
        "roi": -100.0
      }
    ],
    "start_label": "6/1",
    "end_label": "6/30"
  },
  "today_preds": [
    {
      "venue_name": "尼崎",
      "race_no": "9",
      "start_time": "14:33",
      "combo": "6-5-1",
      "actual_combo": "",
      "ev": 9.9,
      "odds": "307.9",
      "prob_pct": "3.2",
      "hit": "",
      "payout": "",
      "final_odds": "",
      "actual_ev": null
    },
    {
      "venue_name": "戸田",
      "race_no": "9",
      "start_time": "14:48",
      "combo": "6-1-3",
      "actual_combo": "",
      "ev": 8.71,
      "odds": "185.1",
      "prob_pct": "4.7",
      "hit": "",
      "payout": "",
      "final_odds": "",
      "actual_ev": null
    },
    {
      "venue_name": "琵琶湖",
      "race_no": "9",
      "start_time": "14:46",
      "combo": "6-5-4",
      "actual_combo": "",
      "ev": 7.04,
      "odds": "269.4",
      "prob_pct": "2.6",
      "hit": "",
      "payout": "",
      "final_odds": "",
      "actual_ev": null
    },
    {
      "venue_name": "常滑",
      "race_no": "11",
      "start_time": "15:35",
      "combo": "2-1-6",
      "actual_combo": "",
      "ev": 4.97,
      "odds": "181.0",
      "prob_pct": "2.8",
      "hit": "",
      "payout": "",
      "final_odds": "",
      "actual_ev": null
    },
    {
      "venue_name": "尼崎",
      "race_no": "11",
      "start_time": "15:39",
      "combo": "2-4-1",
      "actual_combo": "",
      "ev": 3.45,
      "odds": "121.7",
      "prob_pct": "2.8",
      "hit": "",
      "payout": "",
      "final_odds": "",
      "actual_ev": null
    },
    {
      "venue_name": "琵琶湖",
      "race_no": "10",
      "start_time": "15:12",
      "combo": "3-6-4",
      "actual_combo": "",
      "ev": 3.27,
      "odds": "127.9",
      "prob_pct": "2.5",
      "hit": "",
      "payout": "",
      "final_odds": "",
      "actual_ev": null
    },
    {
      "venue_name": "宮島",
      "race_no": "8",
      "start_time": "14:26",
      "combo": "4-3-2",
      "actual_combo": "",
      "ev": 2.04,
      "odds": "44.7",
      "prob_pct": "4.6",
      "hit": "",
      "payout": "",
      "final_odds": "",
      "actual_ev": null
    },
    {
      "venue_name": "多摩川",
      "race_no": "7",
      "start_time": "14:36",
      "combo": "5-1-3",
      "actual_combo": "",
      "ev": 1.99,
      "odds": "72.6",
      "prob_pct": "2.7",
      "hit": "",
      "payout": "",
      "final_odds": "",
      "actual_ev": null
    },
    {
      "venue_name": "常滑",
      "race_no": "10",
      "start_time": "15:02",
      "combo": "2-3-5",
      "actual_combo": "",
      "ev": 1.51,
      "odds": "57.4",
      "prob_pct": "2.6",
      "hit": "",
      "payout": "",
      "final_odds": "",
      "actual_ev": null
    }
  ],
  "pred_days": [
    {
      "date_str": "20260629",
      "date_label": "2026/06/29",
      "is_today": true,
      "preds": [
        {
          "venue_name": "尼崎",
          "race_no": "9",
          "start_time": "14:33",
          "combo": "6-5-1",
          "actual_combo": "",
          "ev": 9.9,
          "odds": "307.9",
          "prob_pct": "3.2",
          "hit": "",
          "payout": "",
          "final_odds": "",
          "actual_ev": null
        },
        {
          "venue_name": "戸田",
          "race_no": "9",
          "start_time": "14:48",
          "combo": "6-1-3",
          "actual_combo": "",
          "ev": 8.71,
          "odds": "185.1",
          "prob_pct": "4.7",
          "hit": "",
          "payout": "",
          "final_odds": "",
          "actual_ev": null
        },
        {
          "venue_name": "琵琶湖",
          "race_no": "9",
          "start_time": "14:46",
          "combo": "6-5-4",
          "actual_combo": "",
          "ev": 7.04,
          "odds": "269.4",
          "prob_pct": "2.6",
          "hit": "",
          "payout": "",
          "final_odds": "",
          "actual_ev": null
        },
        {
          "venue_name": "常滑",
          "race_no": "11",
          "start_time": "15:35",
          "combo": "2-1-6",
          "actual_combo": "",
          "ev": 4.97,
          "odds": "181.0",
          "prob_pct": "2.8",
          "hit": "",
          "payout": "",
          "final_odds": "",
          "actual_ev": null
        },
        {
          "venue_name": "尼崎",
          "race_no": "11",
          "start_time": "15:39",
          "combo": "2-4-1",
          "actual_combo": "",
          "ev": 3.45,
          "odds": "121.7",
          "prob_pct": "2.8",
          "hit": "",
          "payout": "",
          "final_odds": "",
          "actual_ev": null
        },
        {
          "venue_name": "琵琶湖",
          "race_no": "10",
          "start_time": "15:12",
          "combo": "3-6-4",
          "actual_combo": "",
          "ev": 3.27,
          "odds": "127.9",
          "prob_pct": "2.5",
          "hit": "",
          "payout": "",
          "final_odds": "",
          "actual_ev": null
        },
        {
          "venue_name": "宮島",
          "race_no": "8",
          "start_time": "14:26",
          "combo": "4-3-2",
          "actual_combo": "",
          "ev": 2.04,
          "odds": "44.7",
          "prob_pct": "4.6",
          "hit": "",
          "payout": "",
          "final_odds": "",
          "actual_ev": null
        },
        {
          "venue_name": "多摩川",
          "race_no": "7",
          "start_time": "14:36",
          "combo": "5-1-3",
          "actual_combo": "",
          "ev": 1.99,
          "odds": "72.6",
          "prob_pct": "2.7",
          "hit": "",
          "payout": "",
          "final_odds": "",
          "actual_ev": null
        },
        {
          "venue_name": "常滑",
          "race_no": "10",
          "start_time": "15:02",
          "combo": "2-3-5",
          "actual_combo": "",
          "ev": 1.51,
          "odds": "57.4",
          "prob_pct": "2.6",
          "hit": "",
          "payout": "",
          "final_odds": "",
          "actual_ev": null
        }
      ]
    },
    {
      "date_str": "20260628",
      "date_label": "2026/06/28",
      "is_today": false,
      "preds": [
        {
          "venue_name": "江戸川",
          "race_no": "7",
          "start_time": "13:56",
          "combo": "6-2-4",
          "actual_combo": "4-1-2",
          "ev": 21.84,
          "odds": "745.6",
          "prob_pct": "2.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "745.6",
          "actual_ev": 21.846
        },
        {
          "venue_name": "宮島",
          "race_no": "11",
          "start_time": "16:07",
          "combo": "6-2-1",
          "actual_combo": "1-2-5",
          "ev": 17.68,
          "odds": "613.3",
          "prob_pct": "2.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "1763.0",
          "actual_ev": 50.774
        },
        {
          "venue_name": "多摩川",
          "race_no": "9",
          "start_time": "15:41",
          "combo": "6-5-4",
          "actual_combo": "1-2-6",
          "ev": 14.56,
          "odds": "575.8",
          "prob_pct": "2.5",
          "hit": "0",
          "payout": "0",
          "final_odds": "575.8",
          "actual_ev": 14.568
        },
        {
          "venue_name": "大村",
          "race_no": "2",
          "start_time": "15:51",
          "combo": "6-4-3",
          "actual_combo": "2-4-1",
          "ev": 14.51,
          "odds": "453.1",
          "prob_pct": "3.2",
          "hit": "0",
          "payout": "0",
          "final_odds": "453.1",
          "actual_ev": 14.499
        },
        {
          "venue_name": "多摩川",
          "race_no": "6",
          "start_time": "14:04",
          "combo": "6-2-3",
          "actual_combo": "6-4-1",
          "ev": 13.93,
          "odds": "451.4",
          "prob_pct": "3.1",
          "hit": "0",
          "payout": "0",
          "final_odds": "451.4",
          "actual_ev": 13.948
        },
        {
          "venue_name": "平和島",
          "race_no": "6",
          "start_time": "14:28",
          "combo": "6-1-5",
          "actual_combo": "3-1-2",
          "ev": 12.85,
          "odds": "474.1",
          "prob_pct": "2.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "386.8",
          "actual_ev": 10.482
        },
        {
          "venue_name": "大村",
          "race_no": "3",
          "start_time": "16:28",
          "combo": "6-4-3",
          "actual_combo": "3-1-2",
          "ev": 12.76,
          "odds": "496.1",
          "prob_pct": "2.6",
          "hit": "0",
          "payout": "0",
          "final_odds": "533.8",
          "actual_ev": 13.719
        },
        {
          "venue_name": "若松",
          "race_no": "2",
          "start_time": "18:08",
          "combo": "6-5-2",
          "actual_combo": "2-5-3",
          "ev": 12.62,
          "odds": "343.2",
          "prob_pct": "3.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "343.2",
          "actual_ev": 12.63
        },
        {
          "venue_name": "平和島",
          "race_no": "9",
          "start_time": "16:05",
          "combo": "5-3-2",
          "actual_combo": "1-3-5",
          "ev": 10.2,
          "odds": "286.0",
          "prob_pct": "3.6",
          "hit": "0",
          "payout": "0",
          "final_odds": "387.2",
          "actual_ev": 13.823
        },
        {
          "venue_name": "尼崎",
          "race_no": "8",
          "start_time": "13:57",
          "combo": "6-2-1",
          "actual_combo": "2-1-5",
          "ev": 9.99,
          "odds": "347.8",
          "prob_pct": "2.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "347.8",
          "actual_ev": 9.982
        },
        {
          "venue_name": "鳴門",
          "race_no": "11",
          "start_time": "15:53",
          "combo": "5-2-6",
          "actual_combo": "1-2-3",
          "ev": 9.76,
          "odds": "371.4",
          "prob_pct": "2.6",
          "hit": "0",
          "payout": "0",
          "final_odds": "371.4",
          "actual_ev": 9.768
        },
        {
          "venue_name": "蒲郡",
          "race_no": "7",
          "start_time": "18:28",
          "combo": "3-6-1",
          "actual_combo": "1-3-4",
          "ev": 9.33,
          "odds": "349.3",
          "prob_pct": "2.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "624.4",
          "actual_ev": 16.671
        },
        {
          "venue_name": "徳山",
          "race_no": "12",
          "start_time": "14:10",
          "combo": "5-2-1",
          "actual_combo": "1-2-3",
          "ev": 8.43,
          "odds": "309.9",
          "prob_pct": "2.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "309.9",
          "actual_ev": 8.429
        },
        {
          "venue_name": "宮島",
          "race_no": "8",
          "start_time": "14:23",
          "combo": "3-6-1",
          "actual_combo": "4-3-1",
          "ev": 8.39,
          "odds": "140.7",
          "prob_pct": "6.0",
          "hit": "0",
          "payout": "0",
          "final_odds": "212.3",
          "actual_ev": 12.653
        },
        {
          "venue_name": "桐生",
          "race_no": "7",
          "start_time": "18:24",
          "combo": "3-6-1",
          "actual_combo": "1-3-2",
          "ev": 6.12,
          "odds": "207.9",
          "prob_pct": "2.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "249.4",
          "actual_ev": 7.332
        },
        {
          "venue_name": "大村",
          "race_no": "8",
          "start_time": "18:40",
          "combo": "6-1-3",
          "actual_combo": "1-3-6",
          "ev": 5.59,
          "odds": "206.6",
          "prob_pct": "2.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "180.1",
          "actual_ev": 4.881
        },
        {
          "venue_name": "宮島",
          "race_no": "10",
          "start_time": "15:32",
          "combo": "2-3-1",
          "actual_combo": "1-3-5",
          "ev": 4.88,
          "odds": "180.9",
          "prob_pct": "2.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "180.9",
          "actual_ev": 4.884
        },
        {
          "venue_name": "多摩川",
          "race_no": "7",
          "start_time": "14:36",
          "combo": "6-3-1",
          "actual_combo": "1-3-2",
          "ev": 4.87,
          "odds": "178.0",
          "prob_pct": "2.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "261.7",
          "actual_ev": 7.171
        },
        {
          "venue_name": "蒲郡",
          "race_no": "6",
          "start_time": "18:04",
          "combo": "2-4-3",
          "actual_combo": "1-4-2",
          "ev": 4.72,
          "odds": "171.6",
          "prob_pct": "2.8",
          "hit": "0",
          "payout": "0",
          "final_odds": "171.6",
          "actual_ev": 4.719
        },
        {
          "venue_name": "宮島",
          "race_no": "7",
          "start_time": "13:52",
          "combo": "2-4-1",
          "actual_combo": "1-4-2",
          "ev": 4.51,
          "odds": "156.0",
          "prob_pct": "2.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "156.0",
          "actual_ev": 4.508
        },
        {
          "venue_name": "戸田",
          "race_no": "8",
          "start_time": "14:16",
          "combo": "2-4-1",
          "actual_combo": "3-1-4",
          "ev": 4.25,
          "odds": "168.7",
          "prob_pct": "2.5",
          "hit": "0",
          "payout": "0",
          "final_odds": "168.7",
          "actual_ev": 4.251
        },
        {
          "venue_name": "津",
          "race_no": "9",
          "start_time": "14:38",
          "combo": "6-4-2",
          "actual_combo": "1-5-6",
          "ev": 3.67,
          "odds": "100.3",
          "prob_pct": "3.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "167.9",
          "actual_ev": 6.145
        },
        {
          "venue_name": "住之江",
          "race_no": "2",
          "start_time": "15:59",
          "combo": "5-4-1",
          "actual_combo": "4-1-5",
          "ev": 2.93,
          "odds": "71.1",
          "prob_pct": "4.1",
          "hit": "0",
          "payout": "0",
          "final_odds": "71.1",
          "actual_ev": 2.929
        },
        {
          "venue_name": "蒲郡",
          "race_no": "9",
          "start_time": "19:23",
          "combo": "5-1-6",
          "actual_combo": "1-3-5",
          "ev": 2.1,
          "odds": "81.5",
          "prob_pct": "2.6",
          "hit": "0",
          "payout": "0",
          "final_odds": "352.7",
          "actual_ev": 9.1
        },
        {
          "venue_name": "平和島",
          "race_no": "8",
          "start_time": "15:32",
          "combo": "4-2-1",
          "actual_combo": "2-1-4",
          "ev": 1.91,
          "odds": "71.8",
          "prob_pct": "2.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "71.8",
          "actual_ev": 1.91
        }
      ]
    },
    {
      "date_str": "20260627",
      "date_label": "2026/06/27",
      "is_today": false,
      "preds": [
        {
          "venue_name": "大村",
          "race_no": "5",
          "start_time": "17:24",
          "combo": "6-5-4",
          "actual_combo": "1-2-4",
          "ev": 21.18,
          "odds": "758.0",
          "prob_pct": "2.8",
          "hit": "0",
          "payout": "0",
          "final_odds": "758.0",
          "actual_ev": 21.148
        },
        {
          "venue_name": "芦屋",
          "race_no": "12",
          "start_time": "14:00",
          "combo": "6-1-5",
          "actual_combo": "1-4-2",
          "ev": 19.32,
          "odds": "773.4",
          "prob_pct": "2.5",
          "hit": "0",
          "payout": "0",
          "final_odds": "888.5",
          "actual_ev": 22.213
        },
        {
          "venue_name": "桐生",
          "race_no": "5",
          "start_time": "17:37",
          "combo": "6-5-4",
          "actual_combo": "4-1-2",
          "ev": 17.14,
          "odds": "574.1",
          "prob_pct": "3.0",
          "hit": "0",
          "payout": "0",
          "final_odds": "574.1",
          "actual_ev": 17.108
        },
        {
          "venue_name": "蒲郡",
          "race_no": "1",
          "start_time": "15:29",
          "combo": "6-1-3",
          "actual_combo": "3-1-2",
          "ev": 16.7,
          "odds": "512.3",
          "prob_pct": "3.3",
          "hit": "0",
          "payout": "0",
          "final_odds": "512.3",
          "actual_ev": 16.701
        },
        {
          "venue_name": "宮島",
          "race_no": "7",
          "start_time": "13:52",
          "combo": "2-1-6",
          "actual_combo": "1-2-4",
          "ev": 13.35,
          "odds": "513.8",
          "prob_pct": "2.6",
          "hit": "0",
          "payout": "0",
          "final_odds": "513.8",
          "actual_ev": 13.359
        },
        {
          "venue_name": "戸田",
          "race_no": "7",
          "start_time": "13:45",
          "combo": "6-3-1",
          "actual_combo": "1-3-5",
          "ev": 13.22,
          "odds": "484.0",
          "prob_pct": "2.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "484.0",
          "actual_ev": 13.213
        },
        {
          "venue_name": "津",
          "race_no": "7",
          "start_time": "13:36",
          "combo": "6-3-5",
          "actual_combo": "4-3-1",
          "ev": 7.12,
          "odds": "274.9",
          "prob_pct": "2.6",
          "hit": "0",
          "payout": "0",
          "final_odds": "274.9",
          "actual_ev": 7.12
        },
        {
          "venue_name": "江戸川",
          "race_no": "6",
          "start_time": "13:29",
          "combo": "6-3-1",
          "actual_combo": "1-5-3",
          "ev": 6.53,
          "odds": "229.6",
          "prob_pct": "2.8",
          "hit": "0",
          "payout": "0",
          "final_odds": "229.6",
          "actual_ev": 6.521
        },
        {
          "venue_name": "住之江",
          "race_no": "9",
          "start_time": "19:12",
          "combo": "6-2-1",
          "actual_combo": "1-5-3",
          "ev": 6.53,
          "odds": "257.7",
          "prob_pct": "2.5",
          "hit": "0",
          "payout": "0",
          "final_odds": "692.3",
          "actual_ev": 17.515
        },
        {
          "venue_name": "蒲郡",
          "race_no": "7",
          "start_time": "18:33",
          "combo": "5-3-1",
          "actual_combo": "1-4-2",
          "ev": 5.48,
          "odds": "217.6",
          "prob_pct": "2.5",
          "hit": "0",
          "payout": "0",
          "final_odds": "367.7",
          "actual_ev": 9.266
        },
        {
          "venue_name": "大村",
          "race_no": "2",
          "start_time": "15:59",
          "combo": "5-4-2",
          "actual_combo": "2-5-4",
          "ev": 4.64,
          "odds": "181.5",
          "prob_pct": "2.6",
          "hit": "0",
          "payout": "0",
          "final_odds": "58.6",
          "actual_ev": 1.5
        },
        {
          "venue_name": "福岡",
          "race_no": "4",
          "start_time": "13:58",
          "combo": "4-5-1",
          "actual_combo": "1-5-2",
          "ev": 4.58,
          "odds": "144.0",
          "prob_pct": "3.2",
          "hit": "0",
          "payout": "0",
          "final_odds": "144.0",
          "actual_ev": 4.579
        },
        {
          "venue_name": "桐生",
          "race_no": "9",
          "start_time": "19:18",
          "combo": "6-3-5",
          "actual_combo": "4-3-2",
          "ev": 4.24,
          "odds": "165.4",
          "prob_pct": "2.6",
          "hit": "0",
          "payout": "0",
          "final_odds": "314.2",
          "actual_ev": 8.044
        },
        {
          "venue_name": "尼崎",
          "race_no": "8",
          "start_time": "13:53",
          "combo": "6-4-2",
          "actual_combo": "1-4-3",
          "ev": 3.78,
          "odds": "85.5",
          "prob_pct": "4.4",
          "hit": "0",
          "payout": "0",
          "final_odds": "85.5",
          "actual_ev": 3.779
        },
        {
          "venue_name": "大村",
          "race_no": "7",
          "start_time": "18:14",
          "combo": "6-1-3",
          "actual_combo": "3-5-6",
          "ev": 3.78,
          "odds": "151.2",
          "prob_pct": "2.5",
          "hit": "0",
          "payout": "0",
          "final_odds": "650.4",
          "actual_ev": 16.26
        },
        {
          "venue_name": "宮島",
          "race_no": "8",
          "start_time": "14:23",
          "combo": "6-4-1",
          "actual_combo": "4-1-3",
          "ev": 3.73,
          "odds": "145.3",
          "prob_pct": "2.6",
          "hit": "0",
          "payout": "0",
          "final_odds": "259.7",
          "actual_ev": 6.648
        },
        {
          "venue_name": "桐生",
          "race_no": "4",
          "start_time": "17:12",
          "combo": "6-4-1",
          "actual_combo": "4-2-5",
          "ev": 3.69,
          "odds": "128.7",
          "prob_pct": "2.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "105.8",
          "actual_ev": 3.036
        },
        {
          "venue_name": "津",
          "race_no": "8",
          "start_time": "14:07",
          "combo": "4-6-2",
          "actual_combo": "1-5-4",
          "ev": 3.52,
          "odds": "106.0",
          "prob_pct": "3.3",
          "hit": "0",
          "payout": "0",
          "final_odds": "67.4",
          "actual_ev": 2.238
        },
        {
          "venue_name": "桐生",
          "race_no": "10",
          "start_time": "19:44",
          "combo": "3-2-1",
          "actual_combo": "1-3-2",
          "ev": 3.15,
          "odds": "100.0",
          "prob_pct": "3.1",
          "hit": "0",
          "payout": "0",
          "final_odds": "140.4",
          "actual_ev": 4.423
        },
        {
          "venue_name": "福岡",
          "race_no": "6",
          "start_time": "14:56",
          "combo": "4-3-1",
          "actual_combo": "1-2-4",
          "ev": 2.89,
          "odds": "105.8",
          "prob_pct": "2.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "142.0",
          "actual_ev": 3.891
        },
        {
          "venue_name": "大村",
          "race_no": "6",
          "start_time": "17:49",
          "combo": "2-6-3",
          "actual_combo": "1-6-3",
          "ev": 1.78,
          "odds": "70.3",
          "prob_pct": "2.5",
          "hit": "0",
          "payout": "0",
          "final_odds": "70.3",
          "actual_ev": 1.779
        },
        {
          "venue_name": "福岡",
          "race_no": "11",
          "start_time": "17:28",
          "combo": "5-1-4",
          "actual_combo": "2-1-5",
          "ev": 1.67,
          "odds": "62.5",
          "prob_pct": "2.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "171.2",
          "actual_ev": 4.571
        },
        {
          "venue_name": "大村",
          "race_no": "1",
          "start_time": "15:30",
          "combo": "2-1-6",
          "actual_combo": "3-4-1",
          "ev": 1.58,
          "odds": "61.9",
          "prob_pct": "2.5",
          "hit": "0",
          "payout": "0",
          "final_odds": "61.9",
          "actual_ev": 1.578
        },
        {
          "venue_name": "福岡",
          "race_no": "9",
          "start_time": "16:23",
          "combo": "2-3-1",
          "actual_combo": "2-3-5",
          "ev": 1.5,
          "odds": "51.4",
          "prob_pct": "2.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "26.0",
          "actual_ev": 0.757
        },
        {
          "venue_name": "福岡",
          "race_no": "7",
          "start_time": "15:23",
          "combo": "3-5-1",
          "actual_combo": "3-1-4",
          "ev": 1.31,
          "odds": "30.4",
          "prob_pct": "4.3",
          "hit": "0",
          "payout": "0",
          "final_odds": "30.4",
          "actual_ev": 1.316
        }
      ]
    },
    {
      "date_str": "20260626",
      "date_label": "2026/06/26",
      "is_today": false,
      "preds": [
        {
          "venue_name": "児島",
          "race_no": "2",
          "start_time": "11:30",
          "combo": "2-1-3",
          "actual_combo": "4-3-5",
          "ev": 7.86,
          "odds": "147.9",
          "prob_pct": "5.3",
          "hit": "0",
          "payout": "0",
          "final_odds": "80.5",
          "actual_ev": 4.275
        },
        {
          "venue_name": "尼崎",
          "race_no": "4",
          "start_time": "11:53",
          "combo": "2-3-1",
          "actual_combo": "1-2-6",
          "ev": 6.99,
          "odds": "180.9",
          "prob_pct": "3.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "72.2",
          "actual_ev": 2.787
        },
        {
          "venue_name": "唐津",
          "race_no": "4",
          "start_time": "09:57",
          "combo": "3-2-1",
          "actual_combo": "4-1-6",
          "ev": 6.91,
          "odds": "215.7",
          "prob_pct": "3.2",
          "hit": "0",
          "payout": "0",
          "final_odds": "215.7",
          "actual_ev": 6.924
        },
        {
          "venue_name": "唐津",
          "race_no": "5",
          "start_time": "10:23",
          "combo": "2-1-4",
          "actual_combo": "1-2-3",
          "ev": 6.61,
          "odds": "223.9",
          "prob_pct": "2.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "238.5",
          "actual_ev": 7.036
        },
        {
          "venue_name": "津",
          "race_no": "1",
          "start_time": "10:40",
          "combo": "2-1-3",
          "actual_combo": "5-1-3",
          "ev": 5.86,
          "odds": "136.5",
          "prob_pct": "4.3",
          "hit": "0",
          "payout": "0",
          "final_odds": "423.7",
          "actual_ev": 18.219
        },
        {
          "venue_name": "尼崎",
          "race_no": "1",
          "start_time": "10:38",
          "combo": "2-3-1",
          "actual_combo": "1-4-2",
          "ev": 5.83,
          "odds": "109.9",
          "prob_pct": "5.3",
          "hit": "0",
          "payout": "0",
          "final_odds": "104.8",
          "actual_ev": 5.565
        },
        {
          "venue_name": "鳴門",
          "race_no": "3",
          "start_time": "11:44",
          "combo": "2-3-1",
          "actual_combo": "1-2-5",
          "ev": 5.48,
          "odds": "200.1",
          "prob_pct": "2.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "440.2",
          "actual_ev": 12.061
        },
        {
          "venue_name": "津",
          "race_no": "3",
          "start_time": "11:36",
          "combo": "3-2-1",
          "actual_combo": "1-5-2",
          "ev": 5.28,
          "odds": "159.6",
          "prob_pct": "3.3",
          "hit": "0",
          "payout": "0",
          "final_odds": "201.9",
          "actual_ev": 6.683
        },
        {
          "venue_name": "平和島",
          "race_no": "1",
          "start_time": "11:55",
          "combo": "2-5-1",
          "actual_combo": "5-1-4",
          "ev": 5.2,
          "odds": "181.4",
          "prob_pct": "2.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "84.8",
          "actual_ev": 2.434
        },
        {
          "venue_name": "唐津",
          "race_no": "7",
          "start_time": "11:25",
          "combo": "2-3-1",
          "actual_combo": "3-4-2",
          "ev": 5.12,
          "odds": "146.0",
          "prob_pct": "3.5",
          "hit": "0",
          "payout": "0",
          "final_odds": "110.5",
          "actual_ev": 3.879
        },
        {
          "venue_name": "児島",
          "race_no": "1",
          "start_time": "10:58",
          "combo": "2-1-3",
          "actual_combo": "1-3-6",
          "ev": 4.91,
          "odds": "104.7",
          "prob_pct": "4.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "172.5",
          "actual_ev": 8.09
        },
        {
          "venue_name": "宮島",
          "race_no": "1",
          "start_time": "10:46",
          "combo": "2-3-1",
          "actual_combo": "3-1-6",
          "ev": 4.86,
          "odds": "137.1",
          "prob_pct": "3.5",
          "hit": "0",
          "payout": "0",
          "final_odds": "327.3",
          "actual_ev": 11.619
        },
        {
          "venue_name": "唐津",
          "race_no": "6",
          "start_time": "10:55",
          "combo": "2-3-1",
          "actual_combo": "6-2-1",
          "ev": 4.15,
          "odds": "111.0",
          "prob_pct": "3.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "83.9",
          "actual_ev": 3.138
        },
        {
          "venue_name": "尼崎",
          "race_no": "3",
          "start_time": "11:28",
          "combo": "3-2-1",
          "actual_combo": "1-2-3",
          "ev": 3.85,
          "odds": "124.9",
          "prob_pct": "3.1",
          "hit": "0",
          "payout": "0",
          "final_odds": "66.1",
          "actual_ev": 2.036
        },
        {
          "venue_name": "児島",
          "race_no": "3",
          "start_time": "12:00",
          "combo": "2-3-1",
          "actual_combo": "1-2-3",
          "ev": 3.82,
          "odds": "134.2",
          "prob_pct": "2.8",
          "hit": "0",
          "payout": "0",
          "final_odds": "83.3",
          "actual_ev": 2.366
        },
        {
          "venue_name": "尼崎",
          "race_no": "2",
          "start_time": "11:04",
          "combo": "3-2-1",
          "actual_combo": "2-5-6",
          "ev": 3.54,
          "odds": "94.6",
          "prob_pct": "3.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "118.7",
          "actual_ev": 4.439
        },
        {
          "venue_name": "江戸川",
          "race_no": "1",
          "start_time": "11:14",
          "combo": "3-2-1",
          "actual_combo": "1-5-2",
          "ev": 3.27,
          "odds": "68.0",
          "prob_pct": "4.8",
          "hit": "0",
          "payout": "0",
          "final_odds": "39.8",
          "actual_ev": 1.914
        },
        {
          "venue_name": "津",
          "race_no": "2",
          "start_time": "11:08",
          "combo": "2-1-3",
          "actual_combo": "6-1-4",
          "ev": 3.12,
          "odds": "86.0",
          "prob_pct": "3.6",
          "hit": "0",
          "payout": "0",
          "final_odds": "72.0",
          "actual_ev": 2.614
        },
        {
          "venue_name": "江戸川",
          "race_no": "2",
          "start_time": "11:41",
          "combo": "2-3-1",
          "actual_combo": "1-3-6",
          "ev": 2.64,
          "odds": "90.8",
          "prob_pct": "2.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "95.9",
          "actual_ev": 2.791
        },
        {
          "venue_name": "唐津",
          "race_no": "8",
          "start_time": "11:57",
          "combo": "3-1-2",
          "actual_combo": "1-2-5",
          "ev": 2.49,
          "odds": "92.1",
          "prob_pct": "2.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "605.7",
          "actual_ev": 16.354
        }
      ]
    },
    {
      "date_str": "20260625",
      "date_label": "2026/06/25",
      "is_today": false,
      "preds": [
        {
          "venue_name": "津",
          "race_no": "4",
          "start_time": "12:06",
          "combo": "2-5-4",
          "actual_combo": "4-6-5",
          "ev": 7.82,
          "odds": "274.5",
          "prob_pct": "2.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "192.2",
          "actual_ev": 5.478
        },
        {
          "venue_name": "唐津",
          "race_no": "7",
          "start_time": "11:25",
          "combo": "6-5-3",
          "actual_combo": "1-5-4",
          "ev": 4.86,
          "odds": "189.5",
          "prob_pct": "2.6",
          "hit": "0",
          "payout": "0",
          "final_odds": "437.4",
          "actual_ev": 11.241
        },
        {
          "venue_name": "唐津",
          "race_no": "4",
          "start_time": "09:57",
          "combo": "6-2-3",
          "actual_combo": "3-2-6",
          "ev": 2.57,
          "odds": "61.7",
          "prob_pct": "4.2",
          "hit": "0",
          "payout": "0",
          "final_odds": "61.7",
          "actual_ev": 2.567
        },
        {
          "venue_name": "徳山",
          "race_no": "8",
          "start_time": "12:02",
          "combo": "3-5-2",
          "actual_combo": "2-1-3",
          "ev": 2.46,
          "odds": "88.6",
          "prob_pct": "2.8",
          "hit": "0",
          "payout": "0",
          "final_odds": "74.9",
          "actual_ev": 2.075
        },
        {
          "venue_name": "平和島",
          "race_no": "1",
          "start_time": "11:55",
          "combo": "6-4-5",
          "actual_combo": "6-1-2",
          "ev": 2.19,
          "odds": "81.7",
          "prob_pct": "2.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "54.5",
          "actual_ev": 1.466
        }
      ]
    },
    {
      "date_str": "20260624",
      "date_label": "2026/06/24",
      "is_today": false,
      "preds": [
        {
          "venue_name": "三国",
          "race_no": "6",
          "start_time": "10:44",
          "combo": "6-4-1",
          "actual_combo": "1-4-2",
          "ev": 9.47,
          "odds": "347.2",
          "prob_pct": "2.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "201.1",
          "actual_ev": 5.49
        },
        {
          "venue_name": "唐津",
          "race_no": "3",
          "start_time": "09:36",
          "combo": "6-2-1",
          "actual_combo": "1-6-4",
          "ev": 8.78,
          "odds": "232.7",
          "prob_pct": "3.8",
          "hit": "0",
          "payout": "0",
          "final_odds": "232.7",
          "actual_ev": 8.773
        },
        {
          "venue_name": "三国",
          "race_no": "4",
          "start_time": "09:50",
          "combo": "6-1-4",
          "actual_combo": "2-6-3",
          "ev": 6.91,
          "odds": "275.5",
          "prob_pct": "2.5",
          "hit": "0",
          "payout": "0",
          "final_odds": "275.5",
          "actual_ev": 6.915
        },
        {
          "venue_name": "三国",
          "race_no": "5",
          "start_time": "10:18",
          "combo": "6-5-2",
          "actual_combo": "1-2-6",
          "ev": 3.98,
          "odds": "85.2",
          "prob_pct": "4.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "160.0",
          "actual_ev": 7.488
        },
        {
          "venue_name": "唐津",
          "race_no": "5",
          "start_time": "10:30",
          "combo": "5-2-1",
          "actual_combo": "1-2-4",
          "ev": 3.97,
          "odds": "156.5",
          "prob_pct": "2.5",
          "hit": "0",
          "payout": "0",
          "final_odds": "210.4",
          "actual_ev": 5.344
        },
        {
          "venue_name": "鳴門",
          "race_no": "1",
          "start_time": "10:50",
          "combo": "4-3-1",
          "actual_combo": "1-4-6",
          "ev": 2.25,
          "odds": "67.8",
          "prob_pct": "3.3",
          "hit": "0",
          "payout": "0",
          "final_odds": "100.6",
          "actual_ev": 3.33
        }
      ]
    },
    {
      "date_str": "20260623",
      "date_label": "2026/06/23",
      "is_today": false,
      "preds": [
        {
          "venue_name": "蒲郡",
          "race_no": "8",
          "start_time": "18:57",
          "combo": "6-5-1",
          "actual_combo": "2-3-4",
          "ev": 20.78,
          "odds": "2670.0",
          "prob_pct": "0.8",
          "hit": "0",
          "payout": "0",
          "final_odds": "2670.0",
          "actual_ev": 20.826
        },
        {
          "venue_name": "丸亀",
          "race_no": "8",
          "start_time": "18:40",
          "combo": "3-6-4",
          "actual_combo": "4-1-3",
          "ev": 20.45,
          "odds": "1988.0",
          "prob_pct": "1.0",
          "hit": "0",
          "payout": "0",
          "final_odds": "1988.0",
          "actual_ev": 20.476
        },
        {
          "venue_name": "下関",
          "race_no": "8",
          "start_time": "18:49",
          "combo": "6-5-2",
          "actual_combo": "1-2-3",
          "ev": 17.81,
          "odds": "4823.0",
          "prob_pct": "0.4",
          "hit": "0",
          "payout": "0",
          "final_odds": "4823.0",
          "actual_ev": 17.845
        },
        {
          "venue_name": "蒲郡",
          "race_no": "7",
          "start_time": "18:32",
          "combo": "6-4-3",
          "actual_combo": "1-5-3",
          "ev": 17.13,
          "odds": "9999.0",
          "prob_pct": "0.2",
          "hit": "0",
          "payout": "0",
          "final_odds": "9999.0",
          "actual_ev": 16.998
        },
        {
          "venue_name": "下関",
          "race_no": "9",
          "start_time": "19:15",
          "combo": "6-3-1",
          "actual_combo": "1-3-5",
          "ev": 16.52,
          "odds": "1122.0",
          "prob_pct": "1.5",
          "hit": "0",
          "payout": "0",
          "final_odds": "2626.0",
          "actual_ev": 38.602
        },
        {
          "venue_name": "下関",
          "race_no": "11",
          "start_time": "20:09",
          "combo": "6-1-5",
          "actual_combo": "1-5-2",
          "ev": 16.0,
          "odds": "1089.0",
          "prob_pct": "1.5",
          "hit": "0",
          "payout": "0",
          "final_odds": "370.6",
          "actual_ev": 5.448
        },
        {
          "venue_name": "蒲郡",
          "race_no": "12",
          "start_time": "20:45",
          "combo": "6-5-4",
          "actual_combo": "1-5-2",
          "ev": 14.54,
          "odds": "1212.0",
          "prob_pct": "1.2",
          "hit": "0",
          "payout": "0",
          "final_odds": "2352.0",
          "actual_ev": 28.224
        },
        {
          "venue_name": "丸亀",
          "race_no": "12",
          "start_time": "20:30",
          "combo": "6-4-3",
          "actual_combo": "1-2-4",
          "ev": 11.4,
          "odds": "764.8",
          "prob_pct": "1.5",
          "hit": "0",
          "payout": "0",
          "final_odds": "1378.0",
          "actual_ev": 20.532
        },
        {
          "venue_name": "丸亀",
          "race_no": "9",
          "start_time": "19:06",
          "combo": "2-6-4",
          "actual_combo": "1-2-4",
          "ev": 11.32,
          "odds": "1520.0",
          "prob_pct": "0.8",
          "hit": "0",
          "payout": "0",
          "final_odds": "2057.0",
          "actual_ev": 15.428
        },
        {
          "venue_name": "下関",
          "race_no": "12",
          "start_time": "20:38",
          "combo": "5-4-3",
          "actual_combo": "1-3-4",
          "ev": 11.27,
          "odds": "577.6",
          "prob_pct": "1.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "392.6",
          "actual_ev": 7.656
        },
        {
          "venue_name": "蒲郡",
          "race_no": "11",
          "start_time": "20:17",
          "combo": "6-5-2",
          "actual_combo": "1-2-3",
          "ev": 8.62,
          "odds": "1045.0",
          "prob_pct": "0.8",
          "hit": "0",
          "payout": "0",
          "final_odds": "2853.0",
          "actual_ev": 23.395
        },
        {
          "venue_name": "蒲郡",
          "race_no": "10",
          "start_time": "19:50",
          "combo": "6-1-5",
          "actual_combo": "1-5-4",
          "ev": 8.25,
          "odds": "666.5",
          "prob_pct": "1.2",
          "hit": "0",
          "payout": "0",
          "final_odds": "552.1",
          "actual_ev": 6.846
        },
        {
          "venue_name": "下関",
          "race_no": "10",
          "start_time": "19:42",
          "combo": "5-4-2",
          "actual_combo": "1-2-3",
          "ev": 7.71,
          "odds": "680.6",
          "prob_pct": "1.1",
          "hit": "0",
          "payout": "0",
          "final_odds": "1338.0",
          "actual_ev": 15.119
        },
        {
          "venue_name": "丸亀",
          "race_no": "10",
          "start_time": "19:33",
          "combo": "4-6-3",
          "actual_combo": "3-1-6",
          "ev": 7.4,
          "odds": "677.2",
          "prob_pct": "1.1",
          "hit": "0",
          "payout": "0",
          "final_odds": "1340.0",
          "actual_ev": 14.606
        },
        {
          "venue_name": "丸亀",
          "race_no": "11",
          "start_time": "20:00",
          "combo": "2-6-5",
          "actual_combo": "1-3-2",
          "ev": 4.78,
          "odds": "290.2",
          "prob_pct": "1.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "375.9",
          "actual_ev": 6.202
        },
        {
          "venue_name": "蒲郡",
          "race_no": "9",
          "start_time": "19:23",
          "combo": "6-4-1",
          "actual_combo": "1-4-2",
          "ev": 4.76,
          "odds": "1019.0",
          "prob_pct": "0.5",
          "hit": "0",
          "payout": "0",
          "final_odds": "3699.0",
          "actual_ev": 17.385
        }
      ]
    }
  ],
  "weekly_perfs": [
    {
      "week_label": "6/29〜7/5",
      "start": "2026-06-29",
      "end": "2026-07-05",
      "is_current": true,
      "perf": {
        "1.15": {
          "bets": 25,
          "hits": 0,
          "hit_rate": 0.0,
          "invested": 2500,
          "returned": 0,
          "roi": -100.0
        },
        "1.2": {
          "bets": 25,
          "hits": 0,
          "hit_rate": 0.0,
          "invested": 2500,
          "returned": 0,
          "roi": -100.0
        },
        "1.3": {
          "bets": 25,
          "hits": 0,
          "hit_rate": 0.0,
          "invested": 2500,
          "returned": 0,
          "roi": -100.0
        }
      }
    },
    {
      "week_label": "6/22〜6/28",
      "start": "2026-06-22",
      "end": "2026-06-28",
      "is_current": false,
      "perf": {
        "1.15": {
          "bets": 514,
          "hits": 2,
          "hit_rate": 0.4,
          "invested": 51400,
          "returned": 2590,
          "roi": -95.0
        },
        "1.2": {
          "bets": 514,
          "hits": 2,
          "hit_rate": 0.4,
          "invested": 51400,
          "returned": 2590,
          "roi": -95.0
        },
        "1.3": {
          "bets": 514,
          "hits": 2,
          "hit_rate": 0.4,
          "invested": 51400,
          "returned": 2590,
          "roi": -95.0
        }
      }
    },
    {
      "week_label": "6/15〜6/21",
      "start": "2026-06-15",
      "end": "2026-06-21",
      "is_current": false,
      "perf": {
        "1.15": {
          "bets": 641,
          "hits": 13,
          "hit_rate": 2.0,
          "invested": 64100,
          "returned": 0,
          "roi": -100.0
        },
        "1.2": {
          "bets": 641,
          "hits": 13,
          "hit_rate": 2.0,
          "invested": 64100,
          "returned": 0,
          "roi": -100.0
        },
        "1.3": {
          "bets": 641,
          "hits": 13,
          "hit_rate": 2.0,
          "invested": 64100,
          "returned": 0,
          "roi": -100.0
        }
      }
    }
  ],
  "prob_weekly_demo": {
    "total_bets": 0,
    "total_hits": 0,
    "total_invested": 0,
    "total_returned": 0,
    "roi": -100.0,
    "daily": [],
    "start_label": "6/29",
    "end_label": "7/5"
  },
  "prob_monthly_demo": {
    "total_bets": 122,
    "total_hits": 2,
    "total_invested": 12200,
    "total_returned": 2590,
    "roi": -78.8,
    "daily": [
      {
        "date": "6/22",
        "bets": 25,
        "hits": 0,
        "invested": 2500,
        "returned": 0,
        "roi": -100.0
      },
      {
        "date": "6/23",
        "bets": 16,
        "hits": 0,
        "invested": 1600,
        "returned": 0,
        "roi": -100.0
      },
      {
        "date": "6/24",
        "bets": 6,
        "hits": 0,
        "invested": 600,
        "returned": 0,
        "roi": -100.0
      },
      {
        "date": "6/25",
        "bets": 5,
        "hits": 0,
        "invested": 500,
        "returned": 0,
        "roi": -100.0
      },
      {
        "date": "6/26",
        "bets": 20,
        "hits": 2,
        "invested": 2000,
        "returned": 2590,
        "roi": 29.5
      },
      {
        "date": "6/27",
        "bets": 25,
        "hits": 0,
        "invested": 2500,
        "returned": 0,
        "roi": -100.0
      },
      {
        "date": "6/28",
        "bets": 25,
        "hits": 0,
        "invested": 2500,
        "returned": 0,
        "roi": -100.0
      }
    ],
    "start_label": "6/1",
    "end_label": "6/30"
  },
  "prob_pred_days": [
    {
      "date_str": "20260629",
      "date_label": "2026/06/29",
      "is_today": true,
      "preds": [
        {
          "venue_name": "戸田",
          "race_no": "9",
          "start_time": "14:48",
          "combo": "6-1-3",
          "actual_combo": "",
          "ev": 8.71,
          "has_ev": true,
          "odds": "185.1",
          "prob_pct": "4.7",
          "hit": "",
          "payout": "",
          "final_odds": "",
          "actual_ev": null
        },
        {
          "venue_name": "宮島",
          "race_no": "8",
          "start_time": "14:26",
          "combo": "4-3-2",
          "actual_combo": "",
          "ev": 2.04,
          "has_ev": true,
          "odds": "44.7",
          "prob_pct": "4.6",
          "hit": "",
          "payout": "",
          "final_odds": "",
          "actual_ev": null
        },
        {
          "venue_name": "尼崎",
          "race_no": "9",
          "start_time": "14:33",
          "combo": "6-1-5",
          "actual_combo": "",
          "ev": 7.49,
          "has_ev": true,
          "odds": "193.2",
          "prob_pct": "3.9",
          "hit": "",
          "payout": "",
          "final_odds": "",
          "actual_ev": null
        },
        {
          "venue_name": "琵琶湖",
          "race_no": "9",
          "start_time": "14:46",
          "combo": "6-4-5",
          "actual_combo": "",
          "ev": 5.77,
          "has_ev": true,
          "odds": "156.3",
          "prob_pct": "3.7",
          "hit": "",
          "payout": "",
          "final_odds": "",
          "actual_ev": null
        },
        {
          "venue_name": "尼崎",
          "race_no": "11",
          "start_time": "15:39",
          "combo": "2-4-1",
          "actual_combo": "",
          "ev": 3.45,
          "has_ev": true,
          "odds": "121.7",
          "prob_pct": "2.8",
          "hit": "",
          "payout": "",
          "final_odds": "",
          "actual_ev": null
        },
        {
          "venue_name": "常滑",
          "race_no": "11",
          "start_time": "15:35",
          "combo": "2-1-6",
          "actual_combo": "",
          "ev": 4.97,
          "has_ev": true,
          "odds": "181.0",
          "prob_pct": "2.8",
          "hit": "",
          "payout": "",
          "final_odds": "",
          "actual_ev": null
        },
        {
          "venue_name": "多摩川",
          "race_no": "7",
          "start_time": "14:36",
          "combo": "5-1-3",
          "actual_combo": "",
          "ev": 1.99,
          "has_ev": true,
          "odds": "72.6",
          "prob_pct": "2.7",
          "hit": "",
          "payout": "",
          "final_odds": "",
          "actual_ev": null
        },
        {
          "venue_name": "琵琶湖",
          "race_no": "10",
          "start_time": "15:12",
          "combo": "3-4-6",
          "actual_combo": "",
          "ev": 1.49,
          "has_ev": true,
          "odds": "55.3",
          "prob_pct": "2.7",
          "hit": "",
          "payout": "",
          "final_odds": "",
          "actual_ev": null
        },
        {
          "venue_name": "常滑",
          "race_no": "10",
          "start_time": "15:02",
          "combo": "2-3-5",
          "actual_combo": "",
          "ev": 1.51,
          "has_ev": true,
          "odds": "57.4",
          "prob_pct": "2.6",
          "hit": "",
          "payout": "",
          "final_odds": "",
          "actual_ev": null
        }
      ]
    },
    {
      "date_str": "20260628",
      "date_label": "2026/06/28",
      "is_today": false,
      "preds": [
        {
          "venue_name": "宮島",
          "race_no": "8",
          "start_time": "14:23",
          "combo": "3-1-6",
          "actual_combo": "4-3-1",
          "ev": 2.15,
          "has_ev": true,
          "odds": "30.0",
          "prob_pct": "7.1",
          "hit": "0",
          "payout": "0",
          "final_odds": "31.8",
          "actual_ev": 2.274
        },
        {
          "venue_name": "蒲郡",
          "race_no": "6",
          "start_time": "18:04",
          "combo": "4-2-1",
          "actual_combo": "1-4-2",
          "ev": 2.48,
          "has_ev": true,
          "odds": "43.3",
          "prob_pct": "5.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "43.3",
          "actual_ev": 2.481
        },
        {
          "venue_name": "大村",
          "race_no": "2",
          "start_time": "15:51",
          "combo": "6-4-2",
          "actual_combo": "2-4-1",
          "ev": 14.41,
          "has_ev": true,
          "odds": "282.4",
          "prob_pct": "5.1",
          "hit": "0",
          "payout": "0",
          "final_odds": "282.4",
          "actual_ev": 14.402
        },
        {
          "venue_name": "宮島",
          "race_no": "7",
          "start_time": "13:52",
          "combo": "4-1-2",
          "actual_combo": "1-4-2",
          "ev": 1.42,
          "has_ev": true,
          "odds": "28.8",
          "prob_pct": "4.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "28.8",
          "actual_ev": 1.417
        },
        {
          "venue_name": "若松",
          "race_no": "2",
          "start_time": "18:08",
          "combo": "6-2-5",
          "actual_combo": "2-5-3",
          "ev": 12.37,
          "has_ev": true,
          "odds": "269.9",
          "prob_pct": "4.6",
          "hit": "0",
          "payout": "0",
          "final_odds": "269.9",
          "actual_ev": 12.361
        },
        {
          "venue_name": "平和島",
          "race_no": "9",
          "start_time": "16:05",
          "combo": "3-2-5",
          "actual_combo": "1-3-5",
          "ev": 4.39,
          "has_ev": true,
          "odds": "102.4",
          "prob_pct": "4.3",
          "hit": "0",
          "payout": "0",
          "final_odds": "96.1",
          "actual_ev": 4.123
        },
        {
          "venue_name": "住之江",
          "race_no": "2",
          "start_time": "15:59",
          "combo": "5-4-1",
          "actual_combo": "4-1-5",
          "ev": 2.93,
          "has_ev": true,
          "odds": "71.1",
          "prob_pct": "4.1",
          "hit": "0",
          "payout": "0",
          "final_odds": "71.1",
          "actual_ev": 2.929
        },
        {
          "venue_name": "津",
          "race_no": "9",
          "start_time": "14:38",
          "combo": "6-2-4",
          "actual_combo": "1-5-6",
          "ev": 3.04,
          "has_ev": true,
          "odds": "78.1",
          "prob_pct": "3.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "175.8",
          "actual_ev": 6.839
        },
        {
          "venue_name": "多摩川",
          "race_no": "6",
          "start_time": "14:04",
          "combo": "6-3-2",
          "actual_combo": "6-4-1",
          "ev": 10.9,
          "has_ev": true,
          "odds": "282.6",
          "prob_pct": "3.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "282.6",
          "actual_ev": 10.908
        },
        {
          "venue_name": "桐生",
          "race_no": "7",
          "start_time": "18:24",
          "combo": "3-1-6",
          "actual_combo": "1-3-2",
          "ev": 1.5,
          "has_ev": true,
          "odds": "47.0",
          "prob_pct": "3.2",
          "hit": "0",
          "payout": "0",
          "final_odds": "53.1",
          "actual_ev": 1.694
        },
        {
          "venue_name": "尼崎",
          "race_no": "8",
          "start_time": "13:57",
          "combo": "2-6-1",
          "actual_combo": "2-1-5",
          "ev": 3.27,
          "has_ev": true,
          "odds": "103.0",
          "prob_pct": "3.2",
          "hit": "0",
          "payout": "0",
          "final_odds": "103.0",
          "actual_ev": 3.275
        },
        {
          "venue_name": "宮島",
          "race_no": "11",
          "start_time": "16:07",
          "combo": "6-1-2",
          "actual_combo": "1-2-5",
          "ev": 13.0,
          "has_ev": true,
          "odds": "419.2",
          "prob_pct": "3.1",
          "hit": "0",
          "payout": "0",
          "final_odds": "896.9",
          "actual_ev": 27.804
        },
        {
          "venue_name": "江戸川",
          "race_no": "7",
          "start_time": "13:56",
          "combo": "6-4-2",
          "actual_combo": "4-1-2",
          "ev": 19.96,
          "has_ev": true,
          "odds": "647.2",
          "prob_pct": "3.1",
          "hit": "0",
          "payout": "0",
          "final_odds": "647.2",
          "actual_ev": 19.934
        },
        {
          "venue_name": "平和島",
          "race_no": "6",
          "start_time": "14:28",
          "combo": "1-6-5",
          "actual_combo": "3-1-2",
          "ev": 3.17,
          "has_ev": true,
          "odds": "105.1",
          "prob_pct": "3.0",
          "hit": "0",
          "payout": "0",
          "final_odds": "113.1",
          "actual_ev": 3.416
        },
        {
          "venue_name": "徳山",
          "race_no": "12",
          "start_time": "14:10",
          "combo": "2-1-6",
          "actual_combo": "1-2-3",
          "ev": 3.45,
          "has_ev": true,
          "odds": "116.4",
          "prob_pct": "3.0",
          "hit": "0",
          "payout": "0",
          "final_odds": "116.4",
          "actual_ev": 3.445
        },
        {
          "venue_name": "大村",
          "race_no": "3",
          "start_time": "16:28",
          "combo": "3-6-2",
          "actual_combo": "3-1-2",
          "ev": 2.54,
          "has_ev": true,
          "odds": "86.2",
          "prob_pct": "2.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "111.6",
          "actual_ev": 3.292
        },
        {
          "venue_name": "宮島",
          "race_no": "10",
          "start_time": "15:32",
          "combo": "2-3-5",
          "actual_combo": "1-3-5",
          "ev": 4.58,
          "has_ev": true,
          "odds": "159.1",
          "prob_pct": "2.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "159.1",
          "actual_ev": 4.582
        },
        {
          "venue_name": "多摩川",
          "race_no": "7",
          "start_time": "14:36",
          "combo": "6-1-3",
          "actual_combo": "1-3-2",
          "ev": 4.79,
          "has_ev": true,
          "odds": "170.3",
          "prob_pct": "2.8",
          "hit": "0",
          "payout": "0",
          "final_odds": "242.5",
          "actual_ev": 6.814
        },
        {
          "venue_name": "鳴門",
          "race_no": "11",
          "start_time": "15:53",
          "combo": "2-5-6",
          "actual_combo": "1-2-3",
          "ev": 7.5,
          "has_ev": true,
          "odds": "276.5",
          "prob_pct": "2.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "276.5",
          "actual_ev": 7.493
        },
        {
          "venue_name": "大村",
          "race_no": "8",
          "start_time": "18:40",
          "combo": "6-1-3",
          "actual_combo": "1-3-6",
          "ev": 5.59,
          "has_ev": true,
          "odds": "206.6",
          "prob_pct": "2.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "180.1",
          "actual_ev": 4.881
        },
        {
          "venue_name": "蒲郡",
          "race_no": "7",
          "start_time": "18:28",
          "combo": "3-6-1",
          "actual_combo": "1-3-4",
          "ev": 9.33,
          "has_ev": true,
          "odds": "349.3",
          "prob_pct": "2.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "624.4",
          "actual_ev": 16.671
        },
        {
          "venue_name": "平和島",
          "race_no": "8",
          "start_time": "15:32",
          "combo": "4-2-1",
          "actual_combo": "2-1-4",
          "ev": 1.91,
          "has_ev": true,
          "odds": "71.8",
          "prob_pct": "2.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "71.8",
          "actual_ev": 1.91
        },
        {
          "venue_name": "多摩川",
          "race_no": "9",
          "start_time": "15:41",
          "combo": "6-4-5",
          "actual_combo": "1-2-6",
          "ev": 11.8,
          "has_ev": true,
          "odds": "453.8",
          "prob_pct": "2.6",
          "hit": "0",
          "payout": "0",
          "final_odds": "453.8",
          "actual_ev": 11.799
        },
        {
          "venue_name": "蒲郡",
          "race_no": "9",
          "start_time": "19:23",
          "combo": "5-1-6",
          "actual_combo": "1-3-5",
          "ev": 2.1,
          "has_ev": true,
          "odds": "81.5",
          "prob_pct": "2.6",
          "hit": "0",
          "payout": "0",
          "final_odds": "352.7",
          "actual_ev": 9.1
        },
        {
          "venue_name": "戸田",
          "race_no": "8",
          "start_time": "14:16",
          "combo": "2-4-1",
          "actual_combo": "3-1-4",
          "ev": 4.25,
          "has_ev": true,
          "odds": "168.7",
          "prob_pct": "2.5",
          "hit": "0",
          "payout": "0",
          "final_odds": "168.7",
          "actual_ev": 4.251
        }
      ]
    },
    {
      "date_str": "20260627",
      "date_label": "2026/06/27",
      "is_today": false,
      "preds": [
        {
          "venue_name": "桐生",
          "race_no": "9",
          "start_time": "19:18",
          "combo": "3-6-2",
          "actual_combo": "4-3-2",
          "ev": 2.15,
          "has_ev": true,
          "odds": "43.8",
          "prob_pct": "4.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "66.4",
          "actual_ev": 3.254
        },
        {
          "venue_name": "尼崎",
          "race_no": "8",
          "start_time": "13:53",
          "combo": "6-2-4",
          "actual_combo": "1-4-3",
          "ev": 3.56,
          "has_ev": true,
          "odds": "77.4",
          "prob_pct": "4.6",
          "hit": "0",
          "payout": "0",
          "final_odds": "77.4",
          "actual_ev": 3.56
        },
        {
          "venue_name": "福岡",
          "race_no": "7",
          "start_time": "15:23",
          "combo": "3-5-1",
          "actual_combo": "3-1-4",
          "ev": 1.31,
          "has_ev": true,
          "odds": "30.4",
          "prob_pct": "4.3",
          "hit": "0",
          "payout": "0",
          "final_odds": "30.4",
          "actual_ev": 1.316
        },
        {
          "venue_name": "津",
          "race_no": "8",
          "start_time": "14:07",
          "combo": "6-4-2",
          "actual_combo": "1-5-4",
          "ev": 2.45,
          "has_ev": true,
          "odds": "57.9",
          "prob_pct": "4.2",
          "hit": "0",
          "payout": "0",
          "final_odds": "85.3",
          "actual_ev": 3.6
        },
        {
          "venue_name": "桐生",
          "race_no": "5",
          "start_time": "17:37",
          "combo": "5-4-6",
          "actual_combo": "4-1-2",
          "ev": 1.73,
          "has_ev": true,
          "odds": "47.6",
          "prob_pct": "3.6",
          "hit": "0",
          "payout": "0",
          "final_odds": "47.6",
          "actual_ev": 1.723
        },
        {
          "venue_name": "蒲郡",
          "race_no": "1",
          "start_time": "15:29",
          "combo": "1-6-3",
          "actual_combo": "3-1-2",
          "ev": 3.37,
          "has_ev": true,
          "odds": "97.9",
          "prob_pct": "3.4",
          "hit": "0",
          "payout": "0",
          "final_odds": "97.9",
          "actual_ev": 3.368
        },
        {
          "venue_name": "桐生",
          "race_no": "10",
          "start_time": "19:44",
          "combo": "2-3-1",
          "actual_combo": "1-3-2",
          "ev": 2.4,
          "has_ev": true,
          "odds": "71.0",
          "prob_pct": "3.4",
          "hit": "0",
          "payout": "0",
          "final_odds": "68.3",
          "actual_ev": 2.309
        },
        {
          "venue_name": "桐生",
          "race_no": "4",
          "start_time": "17:12",
          "combo": "6-4-2",
          "actual_combo": "4-2-5",
          "ev": 2.34,
          "has_ev": true,
          "odds": "71.1",
          "prob_pct": "3.3",
          "hit": "0",
          "payout": "0",
          "final_odds": "68.2",
          "actual_ev": 2.244
        },
        {
          "venue_name": "福岡",
          "race_no": "4",
          "start_time": "13:58",
          "combo": "5-4-1",
          "actual_combo": "1-5-2",
          "ev": 3.39,
          "has_ev": true,
          "odds": "103.7",
          "prob_pct": "3.3",
          "hit": "0",
          "payout": "0",
          "final_odds": "103.7",
          "actual_ev": 3.391
        },
        {
          "venue_name": "大村",
          "race_no": "5",
          "start_time": "17:24",
          "combo": "5-4-6",
          "actual_combo": "1-2-4",
          "ev": 1.6,
          "has_ev": true,
          "odds": "49.9",
          "prob_pct": "3.2",
          "hit": "0",
          "payout": "0",
          "final_odds": "49.9",
          "actual_ev": 1.597
        },
        {
          "venue_name": "芦屋",
          "race_no": "12",
          "start_time": "14:00",
          "combo": "5-1-6",
          "actual_combo": "1-4-2",
          "ev": 2.49,
          "has_ev": true,
          "odds": "80.6",
          "prob_pct": "3.1",
          "hit": "0",
          "payout": "0",
          "final_odds": "95.0",
          "actual_ev": 2.936
        },
        {
          "venue_name": "大村",
          "race_no": "2",
          "start_time": "15:59",
          "combo": "5-2-4",
          "actual_combo": "2-5-4",
          "ev": 2.2,
          "has_ev": true,
          "odds": "72.6",
          "prob_pct": "3.0",
          "hit": "0",
          "payout": "0",
          "final_odds": "37.8",
          "actual_ev": 1.145
        },
        {
          "venue_name": "福岡",
          "race_no": "6",
          "start_time": "14:56",
          "combo": "4-1-3",
          "actual_combo": "1-2-4",
          "ev": 2.46,
          "has_ev": true,
          "odds": "82.7",
          "prob_pct": "3.0",
          "hit": "0",
          "payout": "0",
          "final_odds": "91.1",
          "actual_ev": 2.715
        },
        {
          "venue_name": "住之江",
          "race_no": "9",
          "start_time": "19:12",
          "combo": "2-6-1",
          "actual_combo": "1-5-3",
          "ev": 5.28,
          "has_ev": true,
          "odds": "179.4",
          "prob_pct": "2.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "225.1",
          "actual_ev": 6.618
        },
        {
          "venue_name": "福岡",
          "race_no": "9",
          "start_time": "16:23",
          "combo": "2-3-1",
          "actual_combo": "2-3-5",
          "ev": 1.5,
          "has_ev": true,
          "odds": "51.4",
          "prob_pct": "2.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "26.0",
          "actual_ev": 0.757
        },
        {
          "venue_name": "蒲郡",
          "race_no": "7",
          "start_time": "18:33",
          "combo": "3-1-5",
          "actual_combo": "1-4-2",
          "ev": 2.31,
          "has_ev": true,
          "odds": "80.7",
          "prob_pct": "2.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "67.7",
          "actual_ev": 1.943
        },
        {
          "venue_name": "江戸川",
          "race_no": "6",
          "start_time": "13:29",
          "combo": "6-3-1",
          "actual_combo": "1-5-3",
          "ev": 6.53,
          "has_ev": true,
          "odds": "229.6",
          "prob_pct": "2.8",
          "hit": "0",
          "payout": "0",
          "final_odds": "229.6",
          "actual_ev": 6.521
        },
        {
          "venue_name": "宮島",
          "race_no": "7",
          "start_time": "13:52",
          "combo": "1-6-2",
          "actual_combo": "1-2-4",
          "ev": 9.46,
          "has_ev": true,
          "odds": "335.0",
          "prob_pct": "2.8",
          "hit": "0",
          "payout": "0",
          "final_odds": "335.0",
          "actual_ev": 9.447
        },
        {
          "venue_name": "戸田",
          "race_no": "7",
          "start_time": "13:45",
          "combo": "6-3-1",
          "actual_combo": "1-3-5",
          "ev": 13.22,
          "has_ev": true,
          "odds": "484.0",
          "prob_pct": "2.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "484.0",
          "actual_ev": 13.213
        },
        {
          "venue_name": "福岡",
          "race_no": "11",
          "start_time": "17:28",
          "combo": "5-1-4",
          "actual_combo": "2-1-5",
          "ev": 1.67,
          "has_ev": true,
          "odds": "62.5",
          "prob_pct": "2.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "171.2",
          "actual_ev": 4.571
        },
        {
          "venue_name": "宮島",
          "race_no": "8",
          "start_time": "14:23",
          "combo": "4-6-2",
          "actual_combo": "4-1-3",
          "ev": 1.78,
          "has_ev": true,
          "odds": "67.0",
          "prob_pct": "2.6",
          "hit": "0",
          "payout": "0",
          "final_odds": "24.5",
          "actual_ev": 0.649
        },
        {
          "venue_name": "津",
          "race_no": "7",
          "start_time": "13:36",
          "combo": "6-3-5",
          "actual_combo": "4-3-1",
          "ev": 7.12,
          "has_ev": true,
          "odds": "274.9",
          "prob_pct": "2.6",
          "hit": "0",
          "payout": "0",
          "final_odds": "274.9",
          "actual_ev": 7.12
        },
        {
          "venue_name": "大村",
          "race_no": "1",
          "start_time": "15:30",
          "combo": "2-1-6",
          "actual_combo": "3-4-1",
          "ev": 1.58,
          "has_ev": true,
          "odds": "61.9",
          "prob_pct": "2.5",
          "hit": "0",
          "payout": "0",
          "final_odds": "61.9",
          "actual_ev": 1.578
        },
        {
          "venue_name": "大村",
          "race_no": "6",
          "start_time": "17:49",
          "combo": "2-6-3",
          "actual_combo": "1-6-3",
          "ev": 1.78,
          "has_ev": true,
          "odds": "70.3",
          "prob_pct": "2.5",
          "hit": "0",
          "payout": "0",
          "final_odds": "70.3",
          "actual_ev": 1.779
        },
        {
          "venue_name": "大村",
          "race_no": "7",
          "start_time": "18:14",
          "combo": "6-1-3",
          "actual_combo": "3-5-6",
          "ev": 3.78,
          "has_ev": true,
          "odds": "151.2",
          "prob_pct": "2.5",
          "hit": "0",
          "payout": "0",
          "final_odds": "650.4",
          "actual_ev": 16.26
        }
      ]
    },
    {
      "date_str": "20260626",
      "date_label": "2026/06/26",
      "is_today": false,
      "preds": [
        {
          "venue_name": "児島",
          "race_no": "2",
          "start_time": "11:30",
          "combo": "1-2-3",
          "actual_combo": "4-3-5",
          "ev": 2.62,
          "has_ev": true,
          "odds": "37.9",
          "prob_pct": "6.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "19.1",
          "actual_ev": 1.318
        },
        {
          "venue_name": "尼崎",
          "race_no": "2",
          "start_time": "11:04",
          "combo": "2-1-3",
          "actual_combo": "2-5-6",
          "ev": 2.88,
          "has_ev": true,
          "odds": "42.4",
          "prob_pct": "6.8",
          "hit": "0",
          "payout": "0",
          "final_odds": "26.2",
          "actual_ev": 1.782
        },
        {
          "venue_name": "尼崎",
          "race_no": "1",
          "start_time": "10:38",
          "combo": "1-2-3",
          "actual_combo": "1-4-2",
          "ev": 1.43,
          "has_ev": true,
          "odds": "21.0",
          "prob_pct": "6.8",
          "hit": "0",
          "payout": "0",
          "final_odds": "19.6",
          "actual_ev": 1.331
        },
        {
          "venue_name": "江戸川",
          "race_no": "1",
          "start_time": "11:14",
          "combo": "2-1-3",
          "actual_combo": "1-5-2",
          "ev": 1.94,
          "has_ev": true,
          "odds": "29.4",
          "prob_pct": "6.6",
          "hit": "0",
          "payout": "0",
          "final_odds": "18.0",
          "actual_ev": 1.186
        },
        {
          "venue_name": "宮島",
          "race_no": "1",
          "start_time": "10:46",
          "combo": "3-1-2",
          "actual_combo": "3-1-6",
          "ev": 3.59,
          "has_ev": true,
          "odds": "57.7",
          "prob_pct": "6.2",
          "hit": "0",
          "payout": "0",
          "final_odds": "35.0",
          "actual_ev": 2.18
        },
        {
          "venue_name": "児島",
          "race_no": "3",
          "start_time": "12:00",
          "combo": "1-2-3",
          "actual_combo": "1-2-3",
          "ev": 1.88,
          "has_ev": true,
          "odds": "33.5",
          "prob_pct": "5.6",
          "hit": "1",
          "payout": "700",
          "final_odds": "7.0",
          "actual_ev": 0.393
        },
        {
          "venue_name": "津",
          "race_no": "3",
          "start_time": "11:36",
          "combo": "2-1-3",
          "actual_combo": "1-5-2",
          "ev": 5.09,
          "has_ev": true,
          "odds": "95.8",
          "prob_pct": "5.3",
          "hit": "0",
          "payout": "0",
          "final_odds": "89.6",
          "actual_ev": 4.758
        },
        {
          "venue_name": "尼崎",
          "race_no": "4",
          "start_time": "11:53",
          "combo": "2-1-3",
          "actual_combo": "1-2-6",
          "ev": 5.61,
          "has_ev": true,
          "odds": "115.1",
          "prob_pct": "4.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "30.2",
          "actual_ev": 1.471
        },
        {
          "venue_name": "児島",
          "race_no": "1",
          "start_time": "10:58",
          "combo": "2-1-3",
          "actual_combo": "1-3-6",
          "ev": 4.91,
          "has_ev": true,
          "odds": "104.7",
          "prob_pct": "4.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "172.5",
          "actual_ev": 8.09
        },
        {
          "venue_name": "唐津",
          "race_no": "6",
          "start_time": "10:55",
          "combo": "2-1-3",
          "actual_combo": "6-2-1",
          "ev": 2.22,
          "has_ev": true,
          "odds": "49.3",
          "prob_pct": "4.5",
          "hit": "0",
          "payout": "0",
          "final_odds": "29.6",
          "actual_ev": 1.335
        },
        {
          "venue_name": "尼崎",
          "race_no": "3",
          "start_time": "11:28",
          "combo": "1-2-3",
          "actual_combo": "1-2-3",
          "ev": 2.12,
          "has_ev": true,
          "odds": "47.6",
          "prob_pct": "4.5",
          "hit": "1",
          "payout": "1890",
          "final_odds": "18.9",
          "actual_ev": 0.841
        },
        {
          "venue_name": "津",
          "race_no": "1",
          "start_time": "10:40",
          "combo": "2-1-3",
          "actual_combo": "5-1-3",
          "ev": 5.86,
          "has_ev": true,
          "odds": "136.5",
          "prob_pct": "4.3",
          "hit": "0",
          "payout": "0",
          "final_odds": "423.7",
          "actual_ev": 18.219
        },
        {
          "venue_name": "津",
          "race_no": "2",
          "start_time": "11:08",
          "combo": "1-3-2",
          "actual_combo": "6-1-4",
          "ev": 2.11,
          "has_ev": true,
          "odds": "49.6",
          "prob_pct": "4.2",
          "hit": "0",
          "payout": "0",
          "final_odds": "20.7",
          "actual_ev": 0.88
        },
        {
          "venue_name": "唐津",
          "race_no": "7",
          "start_time": "11:25",
          "combo": "2-1-4",
          "actual_combo": "3-4-2",
          "ev": 2.92,
          "has_ev": true,
          "odds": "71.3",
          "prob_pct": "4.1",
          "hit": "0",
          "payout": "0",
          "final_odds": "64.2",
          "actual_ev": 2.626
        },
        {
          "venue_name": "唐津",
          "race_no": "4",
          "start_time": "09:57",
          "combo": "2-1-3",
          "actual_combo": "4-1-6",
          "ev": 2.99,
          "has_ev": true,
          "odds": "76.7",
          "prob_pct": "3.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "76.7",
          "actual_ev": 2.991
        },
        {
          "venue_name": "唐津",
          "race_no": "8",
          "start_time": "11:57",
          "combo": "2-1-3",
          "actual_combo": "1-2-5",
          "ev": 2.31,
          "has_ev": true,
          "odds": "65.2",
          "prob_pct": "3.5",
          "hit": "0",
          "payout": "0",
          "final_odds": "453.6",
          "actual_ev": 16.103
        },
        {
          "venue_name": "江戸川",
          "race_no": "2",
          "start_time": "11:41",
          "combo": "2-1-3",
          "actual_combo": "1-3-6",
          "ev": 2.12,
          "has_ev": true,
          "odds": "65.4",
          "prob_pct": "3.2",
          "hit": "0",
          "payout": "0",
          "final_odds": "61.4",
          "actual_ev": 1.996
        },
        {
          "venue_name": "唐津",
          "race_no": "5",
          "start_time": "10:23",
          "combo": "2-1-3",
          "actual_combo": "1-2-3",
          "ev": 6.34,
          "has_ev": true,
          "odds": "196.8",
          "prob_pct": "3.2",
          "hit": "0",
          "payout": "0",
          "final_odds": "202.3",
          "actual_ev": 6.514
        },
        {
          "venue_name": "平和島",
          "race_no": "1",
          "start_time": "11:55",
          "combo": "1-2-5",
          "actual_combo": "5-1-4",
          "ev": 3.44,
          "has_ev": true,
          "odds": "108.8",
          "prob_pct": "3.2",
          "hit": "0",
          "payout": "0",
          "final_odds": "73.8",
          "actual_ev": 2.332
        },
        {
          "venue_name": "鳴門",
          "race_no": "3",
          "start_time": "11:44",
          "combo": "2-1-3",
          "actual_combo": "1-2-5",
          "ev": 3.05,
          "has_ev": true,
          "odds": "104.5",
          "prob_pct": "2.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "209.0",
          "actual_ev": 6.103
        }
      ]
    },
    {
      "date_str": "20260625",
      "date_label": "2026/06/25",
      "is_today": false,
      "preds": [
        {
          "venue_name": "唐津",
          "race_no": "4",
          "start_time": "09:57",
          "combo": "6-3-2",
          "actual_combo": "3-2-6",
          "ev": 2.44,
          "has_ev": true,
          "odds": "56.5",
          "prob_pct": "4.3",
          "hit": "0",
          "payout": "0",
          "final_odds": "56.5",
          "actual_ev": 2.441
        },
        {
          "venue_name": "徳山",
          "race_no": "8",
          "start_time": "12:02",
          "combo": "5-3-2",
          "actual_combo": "2-1-3",
          "ev": 2.28,
          "has_ev": true,
          "odds": "76.6",
          "prob_pct": "3.0",
          "hit": "0",
          "payout": "0",
          "final_odds": "131.3",
          "actual_ev": 3.913
        },
        {
          "venue_name": "津",
          "race_no": "4",
          "start_time": "12:06",
          "combo": "5-2-4",
          "actual_combo": "4-6-5",
          "ev": 6.4,
          "has_ev": true,
          "odds": "219.6",
          "prob_pct": "2.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "426.3",
          "actual_ev": 12.405
        },
        {
          "venue_name": "平和島",
          "race_no": "1",
          "start_time": "11:55",
          "combo": "6-4-5",
          "actual_combo": "6-1-2",
          "ev": 2.19,
          "has_ev": true,
          "odds": "81.7",
          "prob_pct": "2.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "54.5",
          "actual_ev": 1.466
        },
        {
          "venue_name": "唐津",
          "race_no": "7",
          "start_time": "11:25",
          "combo": "6-5-3",
          "actual_combo": "1-5-4",
          "ev": 4.86,
          "has_ev": true,
          "odds": "189.5",
          "prob_pct": "2.6",
          "hit": "0",
          "payout": "0",
          "final_odds": "437.4",
          "actual_ev": 11.241
        }
      ]
    },
    {
      "date_str": "20260624",
      "date_label": "2026/06/24",
      "is_today": false,
      "preds": [
        {
          "venue_name": "三国",
          "race_no": "5",
          "start_time": "10:18",
          "combo": "6-5-3",
          "actual_combo": "1-2-6",
          "ev": 3.57,
          "has_ev": true,
          "odds": "61.3",
          "prob_pct": "5.8",
          "hit": "0",
          "payout": "0",
          "final_odds": "102.0",
          "actual_ev": 5.936
        },
        {
          "venue_name": "三国",
          "race_no": "4",
          "start_time": "09:50",
          "combo": "6-1-5",
          "actual_combo": "2-6-3",
          "ev": 4.31,
          "has_ev": true,
          "odds": "87.4",
          "prob_pct": "4.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "87.4",
          "actual_ev": 4.309
        },
        {
          "venue_name": "唐津",
          "race_no": "3",
          "start_time": "09:36",
          "combo": "6-1-2",
          "actual_combo": "1-6-4",
          "ev": 5.24,
          "has_ev": true,
          "odds": "125.3",
          "prob_pct": "4.2",
          "hit": "0",
          "payout": "0",
          "final_odds": "125.3",
          "actual_ev": 5.238
        },
        {
          "venue_name": "鳴門",
          "race_no": "1",
          "start_time": "10:50",
          "combo": "4-1-3",
          "actual_combo": "1-4-6",
          "ev": 1.4,
          "has_ev": true,
          "odds": "40.5",
          "prob_pct": "3.4",
          "hit": "0",
          "payout": "0",
          "final_odds": "57.9",
          "actual_ev": 1.992
        },
        {
          "venue_name": "三国",
          "race_no": "6",
          "start_time": "10:44",
          "combo": "6-4-3",
          "actual_combo": "1-4-2",
          "ev": 3.54,
          "has_ev": true,
          "odds": "118.2",
          "prob_pct": "3.0",
          "hit": "0",
          "payout": "0",
          "final_odds": "100.1",
          "actual_ev": 3.003
        },
        {
          "venue_name": "唐津",
          "race_no": "5",
          "start_time": "10:30",
          "combo": "2-5-1",
          "actual_combo": "1-2-4",
          "ev": 2.22,
          "has_ev": true,
          "odds": "83.1",
          "prob_pct": "2.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "132.2",
          "actual_ev": 3.53
        }
      ]
    },
    {
      "date_str": "20260623",
      "date_label": "2026/06/23",
      "is_today": false,
      "preds": [
        {
          "venue_name": "丸亀",
          "race_no": "9",
          "start_time": "19:06",
          "combo": "4-6-1",
          "actual_combo": "1-2-4",
          "ev": 7.34,
          "has_ev": true,
          "odds": "198.0",
          "prob_pct": "3.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "222.6",
          "actual_ev": 8.258
        },
        {
          "venue_name": "蒲郡",
          "race_no": "8",
          "start_time": "18:57",
          "combo": "6-2-5",
          "actual_combo": "2-3-4",
          "ev": 20.64,
          "has_ev": true,
          "odds": "846.9",
          "prob_pct": "2.4",
          "hit": "0",
          "payout": "0",
          "final_odds": "846.9",
          "actual_ev": 20.664
        },
        {
          "venue_name": "下関",
          "race_no": "12",
          "start_time": "20:38",
          "combo": "5-4-3",
          "actual_combo": "1-3-4",
          "ev": 11.27,
          "has_ev": true,
          "odds": "577.6",
          "prob_pct": "1.9",
          "hit": "0",
          "payout": "0",
          "final_odds": "392.6",
          "actual_ev": 7.656
        },
        {
          "venue_name": "蒲郡",
          "race_no": "12",
          "start_time": "20:45",
          "combo": "6-1-5",
          "actual_combo": "1-5-2",
          "ev": 10.65,
          "has_ev": true,
          "odds": "600.7",
          "prob_pct": "1.8",
          "hit": "0",
          "payout": "0",
          "final_odds": "808.7",
          "actual_ev": 14.314
        },
        {
          "venue_name": "丸亀",
          "race_no": "12",
          "start_time": "20:30",
          "combo": "6-3-4",
          "actual_combo": "1-2-4",
          "ev": 9.32,
          "has_ev": true,
          "odds": "551.3",
          "prob_pct": "1.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "1103.0",
          "actual_ev": 18.641
        },
        {
          "venue_name": "下関",
          "race_no": "11",
          "start_time": "20:09",
          "combo": "5-6-1",
          "actual_combo": "1-5-2",
          "ev": 11.69,
          "has_ev": true,
          "odds": "697.3",
          "prob_pct": "1.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "965.1",
          "actual_ev": 16.214
        },
        {
          "venue_name": "丸亀",
          "race_no": "11",
          "start_time": "20:00",
          "combo": "2-6-5",
          "actual_combo": "1-3-2",
          "ev": 4.78,
          "has_ev": true,
          "odds": "290.2",
          "prob_pct": "1.7",
          "hit": "0",
          "payout": "0",
          "final_odds": "375.9",
          "actual_ev": 6.202
        },
        {
          "venue_name": "蒲郡",
          "race_no": "9",
          "start_time": "19:23",
          "combo": "5-4-1",
          "actual_combo": "1-4-2",
          "ev": 3.27,
          "has_ev": true,
          "odds": "201.2",
          "prob_pct": "1.6",
          "hit": "0",
          "payout": "0",
          "final_odds": "572.3",
          "actual_ev": 9.328
        },
        {
          "venue_name": "下関",
          "race_no": "9",
          "start_time": "19:15",
          "combo": "6-3-1",
          "actual_combo": "1-3-5",
          "ev": 16.52,
          "has_ev": true,
          "odds": "1122.0",
          "prob_pct": "1.5",
          "hit": "0",
          "payout": "0",
          "final_odds": "2626.0",
          "actual_ev": 38.602
        },
        {
          "venue_name": "下関",
          "race_no": "10",
          "start_time": "19:42",
          "combo": "4-3-2",
          "actual_combo": "1-2-3",
          "ev": 7.6,
          "has_ev": true,
          "odds": "521.1",
          "prob_pct": "1.5",
          "hit": "0",
          "payout": "0",
          "final_odds": "385.8",
          "actual_ev": 5.633
        },
        {
          "venue_name": "丸亀",
          "race_no": "10",
          "start_time": "19:33",
          "combo": "6-4-3",
          "actual_combo": "3-1-6",
          "ev": 7.12,
          "has_ev": true,
          "odds": "548.2",
          "prob_pct": "1.3",
          "hit": "0",
          "payout": "0",
          "final_odds": "795.2",
          "actual_ev": 10.338
        },
        {
          "venue_name": "蒲郡",
          "race_no": "10",
          "start_time": "19:50",
          "combo": "6-1-3",
          "actual_combo": "1-5-4",
          "ev": 6.99,
          "has_ev": true,
          "odds": "558.4",
          "prob_pct": "1.2",
          "hit": "0",
          "payout": "0",
          "final_odds": "611.3",
          "actual_ev": 7.641
        },
        {
          "venue_name": "蒲郡",
          "race_no": "11",
          "start_time": "20:17",
          "combo": "2-6-5",
          "actual_combo": "1-2-3",
          "ev": 7.08,
          "has_ev": true,
          "odds": "688.1",
          "prob_pct": "1.0",
          "hit": "0",
          "payout": "0",
          "final_odds": "2248.0",
          "actual_ev": 23.154
        },
        {
          "venue_name": "丸亀",
          "race_no": "8",
          "start_time": "18:40",
          "combo": "3-6-4",
          "actual_combo": "4-1-3",
          "ev": 20.45,
          "has_ev": true,
          "odds": "1988.0",
          "prob_pct": "1.0",
          "hit": "0",
          "payout": "0",
          "final_odds": "1988.0",
          "actual_ev": 20.476
        },
        {
          "venue_name": "下関",
          "race_no": "8",
          "start_time": "18:49",
          "combo": "6-1-5",
          "actual_combo": "1-2-3",
          "ev": 17.66,
          "has_ev": true,
          "odds": "3842.0",
          "prob_pct": "0.5",
          "hit": "0",
          "payout": "0",
          "final_odds": "3842.0",
          "actual_ev": 17.673
        },
        {
          "venue_name": "蒲郡",
          "race_no": "7",
          "start_time": "18:32",
          "combo": "6-4-5",
          "actual_combo": "1-5-3",
          "ev": 15.87,
          "has_ev": true,
          "odds": "8411.0",
          "prob_pct": "0.2",
          "hit": "0",
          "payout": "0",
          "final_odds": "8411.0",
          "actual_ev": 15.981
        }
      ]
    }
  ],
  "prob_weekly_perfs": [
    {
      "week_label": "6/29〜7/5",
      "start": "2026-06-29",
      "end": "2026-07-05",
      "is_current": true,
      "perf": {
        "all": {
          "label": "全件（EV不問）",
          "bets": 0,
          "hits": 0,
          "hit_rate": 0.0,
          "invested": 0,
          "returned": 0,
          "roi": -100.0
        },
        "ev": {
          "label": "EV≥1.3のみ",
          "bets": 0,
          "hits": 0,
          "hit_rate": 0.0,
          "invested": 0,
          "returned": 0,
          "roi": -100.0
        }
      }
    },
    {
      "week_label": "6/22〜6/28",
      "start": "2026-06-22",
      "end": "2026-06-28",
      "is_current": false,
      "perf": {
        "all": {
          "label": "全件（EV不問）",
          "bets": 122,
          "hits": 2,
          "hit_rate": 1.6,
          "invested": 12200,
          "returned": 2590,
          "roi": -78.8
        },
        "ev": {
          "label": "EV≥1.3のみ",
          "bets": 122,
          "hits": 2,
          "hit_rate": 1.6,
          "invested": 12200,
          "returned": 2590,
          "roi": -78.8
        }
      }
    }
  ],
  "features": [
    {
      "name": "出走表スクレイピング",
      "desc": "boatrace.jp から全開催場の出走表・直前情報を自動取得"
    },
    {
      "name": "3連単EV計算",
      "desc": "全120通りの期待値（推定確率×オッズ）を算出"
    },
    {
      "name": "オッズ収束フィルター",
      "desc": "発走2時間以内のレースのみ分析（オッズ安定後）"
    },
    {
      "name": "推奨レース絞り込み",
      "desc": "EV≥1.3 の組み合わせを全件推奨（1レース最高EV1件）"
    },
    {
      "name": "結果自動照合",
      "desc": "当日夕方に全結果を取得し予測と照合・的中フラグを記録"
    },
    {
      "name": "回収率検証",
      "desc": "EV閾値1.15/1.20/1.30別に的中率・回収率を週次集計"
    },
    {
      "name": "MLモデル学習",
      "desc": "ロジスティック回帰による的中確率の補正学習（50件以上で起動）"
    },
    {
      "name": "メール通知",
      "desc": "朝の予測と夕方の検証結果をGmail経由で自動送信"
    },
    {
      "name": "デモ収益シミュレーション",
      "desc": "推奨レースに仮想100円投票した場合の週次・月次リターンを計算"
    },
    {
      "name": "ダッシュボード自動更新",
      "desc": "予測実行後にGitHub Pagesへ自動プッシュ"
    }
  ]
};
